import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-demand-response-capacity-payment-recovery",
  "engine": "recovery",
  "title": "Demand Response & Capacity Payment Recovery",
  "shortTitle": "Demand Response and Capacity Payment Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through demand response & capacity payment recovery",
  "industry": "Grid Services Revenue Recovery",
  "uiPort": 4624,
  "apiPort": 5624,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Demand Response & Capacity Payment Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect program tariffs, enrolled sites, assets, capacity commitments, interval meters, baselines, events, performance, availability, capacity, penalties, aggregator fees, statements, and payments in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "paidAmount",
    "expectedKey": "earnedAmount",
    "actualLabel": "Paid Grid Revenue",
    "expectedLabel": "Calculated Earned Revenue",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Demand Response & Capacity Payment Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("program-tariff-library","DRC01","Program tariff library","Execute program tariff library using program tariffs, enrolled sites, assets, capacity commitments, interval meters, baselines, events, performance, availability, capacity, penalties, aggregator fees, statements, and payments.","Produce a governed program tariff library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Enrolled Site","text","Program / Enrolled Site · Standard Case"],["caseReference","Program tariff library Reference","text","DRC01-2026-001"],["paidAmount","Paid Grid Revenue","currency",1030500],["earnedAmount","Calculated Earned Revenue","currency",1215990],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Program tariff library case","Site asset registry case","Enrollment capacity commitment case","Interval meter ingestion case","Baseline calculation case"]}),
feature("site-asset-registry","DRC02","Site asset registry","Execute site asset registry using program tariffs, enrolled sites, assets, capacity commitments, interval meters, baselines, events, performance, availability, capacity, penalties, aggregator fees, statements, and payments.","Produce a governed site asset registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Enrolled Site","text","Program / Enrolled Site · Standard Case"],["caseReference","Site asset registry Reference","text","DRC02-2026-001"],["paidAmount","Paid Grid Revenue","currency",1030500],["earnedAmount","Calculated Earned Revenue","currency",1215990],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Program tariff library case","Site asset registry case","Enrollment capacity commitment case","Interval meter ingestion case","Baseline calculation case"]}),
feature("enrollment-capacity-commitment","DRC03","Enrollment capacity commitment","Execute enrollment capacity commitment using program tariffs, enrolled sites, assets, capacity commitments, interval meters, baselines, events, performance, availability, capacity, penalties, aggregator fees, statements, and payments.","Produce a governed enrollment capacity commitment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Enrolled Site","text","Program / Enrolled Site · Standard Case"],["caseReference","Enrollment capacity commitment Reference","text","DRC03-2026-001"],["paidAmount","Paid Grid Revenue","currency",1030500],["earnedAmount","Calculated Earned Revenue","currency",1215990],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Program tariff library case","Site asset registry case","Enrollment capacity commitment case","Interval meter ingestion case","Baseline calculation case"]}),
feature("interval-meter-ingestion","DRC04","Interval meter ingestion","Execute interval meter ingestion using program tariffs, enrolled sites, assets, capacity commitments, interval meters, baselines, events, performance, availability, capacity, penalties, aggregator fees, statements, and payments.","Produce a governed interval meter ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Enrolled Site","text","Program / Enrolled Site · Standard Case"],["caseReference","Interval meter ingestion Reference","text","DRC04-2026-001"],["paidAmount","Paid Grid Revenue","currency",1030500],["earnedAmount","Calculated Earned Revenue","currency",1215990],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Program tariff library case","Site asset registry case","Enrollment capacity commitment case","Interval meter ingestion case","Baseline calculation case"]}),
feature("baseline-calculation","DRC05","Baseline calculation","Execute baseline calculation using program tariffs, enrolled sites, assets, capacity commitments, interval meters, baselines, events, performance, availability, capacity, penalties, aggregator fees, statements, and payments.","Produce a governed baseline calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Enrolled Site","text","Program / Enrolled Site · Standard Case"],["caseReference","Baseline calculation Reference","text","DRC05-2026-001"],["paidAmount","Paid Grid Revenue","currency",1030500],["earnedAmount","Calculated Earned Revenue","currency",1215990],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Program tariff library case","Site asset registry case","Enrollment capacity commitment case","Interval meter ingestion case","Baseline calculation case"]}),
feature("event-notification-tracking","DRC06","Event notification tracking","Execute event notification tracking using program tariffs, enrolled sites, assets, capacity commitments, interval meters, baselines, events, performance, availability, capacity, penalties, aggregator fees, statements, and payments.","Produce a governed event notification tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Enrolled Site","text","Program / Enrolled Site · Standard Case"],["caseReference","Event notification tracking Reference","text","DRC06-2026-001"],["paidAmount","Paid Grid Revenue","currency",1030500],["earnedAmount","Calculated Earned Revenue","currency",1215990],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Program tariff library case","Site asset registry case","Enrollment capacity commitment case","Interval meter ingestion case","Baseline calculation case"]}),
feature("performance-calculation","DRC07","Performance calculation","Execute performance calculation using program tariffs, enrolled sites, assets, capacity commitments, interval meters, baselines, events, performance, availability, capacity, penalties, aggregator fees, statements, and payments.","Produce a governed performance calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Enrolled Site","text","Program / Enrolled Site · Standard Case"],["caseReference","Performance calculation Reference","text","DRC07-2026-001"],["paidAmount","Paid Grid Revenue","currency",1030500],["earnedAmount","Calculated Earned Revenue","currency",1215990],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Program tariff library case","Site asset registry case","Enrollment capacity commitment case","Interval meter ingestion case","Baseline calculation case"]}),
feature("availability-payment","DRC08","Availability payment","Execute availability payment using program tariffs, enrolled sites, assets, capacity commitments, interval meters, baselines, events, performance, availability, capacity, penalties, aggregator fees, statements, and payments.","Produce a governed availability payment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Enrolled Site","text","Program / Enrolled Site · Standard Case"],["caseReference","Availability payment Reference","text","DRC08-2026-001"],["paidAmount","Paid Grid Revenue","currency",1030500],["earnedAmount","Calculated Earned Revenue","currency",1215990],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Program tariff library case","Site asset registry case","Enrollment capacity commitment case","Interval meter ingestion case","Baseline calculation case"]}),
feature("capacity-payment","DRC09","Capacity payment","Execute capacity payment using program tariffs, enrolled sites, assets, capacity commitments, interval meters, baselines, events, performance, availability, capacity, penalties, aggregator fees, statements, and payments.","Produce a governed capacity payment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Enrolled Site","text","Program / Enrolled Site · Standard Case"],["caseReference","Capacity payment Reference","text","DRC09-2026-001"],["paidAmount","Paid Grid Revenue","currency",1030500],["earnedAmount","Calculated Earned Revenue","currency",1215990],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Program tariff library case","Site asset registry case","Enrollment capacity commitment case","Interval meter ingestion case","Baseline calculation case"]}),
feature("penalty-validation","DRC10","Penalty validation","Execute penalty validation using program tariffs, enrolled sites, assets, capacity commitments, interval meters, baselines, events, performance, availability, capacity, penalties, aggregator fees, statements, and payments.","Produce a governed penalty validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Enrolled Site","text","Program / Enrolled Site · Standard Case"],["caseReference","Penalty validation Reference","text","DRC10-2026-001"],["paidAmount","Paid Grid Revenue","currency",1030500],["earnedAmount","Calculated Earned Revenue","currency",1215990],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Program tariff library case","Site asset registry case","Enrollment capacity commitment case","Interval meter ingestion case","Baseline calculation case"]}),
feature("aggregator-fee-audit","DRC11","Aggregator fee audit","Execute aggregator fee audit using program tariffs, enrolled sites, assets, capacity commitments, interval meters, baselines, events, performance, availability, capacity, penalties, aggregator fees, statements, and payments.","Produce a governed aggregator fee audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Enrolled Site","text","Program / Enrolled Site · Standard Case"],["caseReference","Aggregator fee audit Reference","text","DRC11-2026-001"],["paidAmount","Paid Grid Revenue","currency",1030500],["earnedAmount","Calculated Earned Revenue","currency",1215990],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Program tariff library case","Site asset registry case","Enrollment capacity commitment case","Interval meter ingestion case","Baseline calculation case"]}),
feature("settlement-statement-matching","DRC12","Settlement statement matching","Execute settlement statement matching using program tariffs, enrolled sites, assets, capacity commitments, interval meters, baselines, events, performance, availability, capacity, penalties, aggregator fees, statements, and payments.","Produce a governed settlement statement matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Enrolled Site","text","Program / Enrolled Site · Standard Case"],["caseReference","Settlement statement matching Reference","text","DRC12-2026-001"],["paidAmount","Paid Grid Revenue","currency",1030500],["earnedAmount","Calculated Earned Revenue","currency",1215990],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Program tariff library case","Site asset registry case","Enrollment capacity commitment case","Interval meter ingestion case","Baseline calculation case"]}),
feature("dispute-correction-workflow","DRC13","Dispute correction workflow","Execute dispute correction workflow using program tariffs, enrolled sites, assets, capacity commitments, interval meters, baselines, events, performance, availability, capacity, penalties, aggregator fees, statements, and payments.","Produce a governed dispute correction workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Enrolled Site","text","Program / Enrolled Site · Standard Case"],["caseReference","Dispute correction workflow Reference","text","DRC13-2026-001"],["paidAmount","Paid Grid Revenue","currency",1030500],["earnedAmount","Calculated Earned Revenue","currency",1215990],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Program tariff library case","Site asset registry case","Enrollment capacity commitment case","Interval meter ingestion case","Baseline calculation case"]}),
feature("payment-reconciliation","DRC14","Payment reconciliation","Execute payment reconciliation using program tariffs, enrolled sites, assets, capacity commitments, interval meters, baselines, events, performance, availability, capacity, penalties, aggregator fees, statements, and payments.","Produce a governed payment reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Enrolled Site","text","Program / Enrolled Site · Standard Case"],["caseReference","Payment reconciliation Reference","text","DRC14-2026-001"],["paidAmount","Paid Grid Revenue","currency",1030500],["earnedAmount","Calculated Earned Revenue","currency",1215990],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Program tariff library case","Site asset registry case","Enrollment capacity commitment case","Interval meter ingestion case","Baseline calculation case"]}),
feature("site-program-analytics","DRC15","Site program analytics","Execute site program analytics using program tariffs, enrolled sites, assets, capacity commitments, interval meters, baselines, events, performance, availability, capacity, penalties, aggregator fees, statements, and payments.","Produce a governed site program analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Program / Enrolled Site","text","Program / Enrolled Site · Standard Case"],["caseReference","Site program analytics Reference","text","DRC15-2026-001"],["paidAmount","Paid Grid Revenue","currency",1030500],["earnedAmount","Calculated Earned Revenue","currency",1215990],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Program tariff library case","Site asset registry case","Enrollment capacity commitment case","Interval meter ingestion case","Baseline calculation case"]})
]);
